# Generated by Django 5.0.2 on 2024-02-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=8)),
                ('rpwd', models.CharField(max_length=8)),
            ],
        ),
    ]
