# Generated by Django 5.0.2 on 2024-02-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
