# Generated by Django 5.0.2 on 2024-02-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_books'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
