# Generated by Django 5.0.2 on 2024-02-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_books_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.AddField(
            model_name='books',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
