# Generated by Django 5.0.2 on 2024-02-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_cart_books_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author',
        ),
    ]
