# Generated by Django 5.0.2 on 2024-02-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
