# Generated by Django 5.0.2 on 2024-02-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_buyer_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
