# Generated by Django 5.0.2 on 2024-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cart_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='book',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='qty',
        ),
        migrations.AddField(
            model_name='buyer',
            name='date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='mode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
