# Generated by Django 5.0.2 on 2024-02-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_buyer_book_remove_buyer_qty_buyer_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
