# Generated by Django 5.0.2 on 2024-02-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
