# Generated by Django 5.0.2 on 2024-02-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_buyer_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
