# Generated by Django 5.0.2 on 2024-02-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_delete_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('purchased_book', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
    ]
