# Generated by Django 5.0.2 on 2024-02-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='purchased_book',
        ),
    ]
